import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Feed from "@/components/Feed";
import Widget from "@/components/Widget";
export default function Home({ newsResults }) {
  return (
    <>
      <Head>
        <title> Twitter clone </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className="flex min-h-screen mx-auto ">
        {" "}
        {/* Side bar */}
        <Sidebar />
        {/* Feedback */}
        <Feed />
        {/* Widgets */} <Widget news={newsResults.articles} />
      </main>{" "}
    </>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/health/us.json
export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/health/us.json"
  )
    .then((response) => response.json())
    .catch((err) => err.json());
  return {
    props: {
      newsResults,
    },
  };
}
